/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssetClassRead */
    AssetClassRead: {
      /** Attribute Schema */
      attribute_schema?: {
        [key: string]: unknown;
      };
      /** Code */
      code: string;
      /**
       * Color
       * @default null
       */
      color: string | null;
      /**
       * Default Criticality
       * @default null
       */
      default_criticality: number | null;
      /** Domain */
      domain: string;
      /** Geometry Type */
      geometry_type: string;
      /**
       * Icon
       * @default null
       */
      icon: string | null;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name: string;
    };
    /** AssetCreate */
    AssetCreate: {
      /**
       * Asset Uid
       * @default null
       */
      asset_uid: string | null;
      /** Attrs */
      attrs?: {
        [key: string]: unknown;
      };
      /** Class Code */
      class_code: string;
      /**
       * Condition
       * @default null
       */
      condition: number | null;
      /**
       * Criticality
       * @default null
       */
      criticality: number | null;
      /**
       * Decommission Date
       * @default null
       */
      decommission_date: string | null;
      /**
       * Depth M
       * @default null
       */
      depth_m: number | string | null;
      /**
       * Diameter Mm
       * @default null
       */
      diameter_mm: number | null;
      /** Geometry */
      geometry:
        | components["schemas"]["Point"]
        | components["schemas"]["LineString"]
        | components["schemas"]["Polygon"];
      /**
       * Install Date
       * @default null
       */
      install_date: string | null;
      /**
       * Length M
       * @default null
       */
      length_m: number | string | null;
      /**
       * Manufacturer
       * @default null
       */
      manufacturer: string | null;
      /**
       * Material
       * @default null
       */
      material: string | null;
      /**
       * Model
       * @default null
       */
      model: string | null;
      /**
       * Notes
       * @default null
       */
      notes: string | null;
      /**
       * Serial Number
       * @default null
       */
      serial_number: string | null;
      /**
       * Status
       * @default active
       * @enum {string}
       */
      status: "active" | "abandoned" | "removed" | "proposed";
      /**
       * Warranty Until
       * @default null
       */
      warranty_until: string | null;
    };
    /** AssetHistoryEntry */
    AssetHistoryEntry: {
      /** Action */
      action: string;
      /**
       * After
       * @default null
       */
      after: {
        [key: string]: unknown;
      } | null;
      /**
       * Before
       * @default null
       */
      before: {
        [key: string]: unknown;
      } | null;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /**
       * User Full Name
       * @default null
       */
      user_full_name: string | null;
      /**
       * User Uid
       * @default null
       */
      user_uid: string | null;
    };
    /** AssetHistoryResponse */
    AssetHistoryResponse: {
      /** Items */
      items: components["schemas"]["AssetHistoryEntry"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** AssetListResponse */
    AssetListResponse: {
      /** Items */
      items: components["schemas"]["AssetRead"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** AssetRead */
    AssetRead: {
      /** Asset Uid */
      asset_uid: string;
      /** Attrs */
      attrs?: {
        [key: string]: unknown;
      };
      /** Class Code */
      class_code: string;
      /**
       * Condition
       * @default null
       */
      condition: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Criticality
       * @default null
       */
      criticality: number | null;
      /**
       * Decommission Date
       * @default null
       */
      decommission_date: string | null;
      /**
       * Depth M
       * @default null
       */
      depth_m: number | string | null;
      /**
       * Diameter Mm
       * @default null
       */
      diameter_mm: number | null;
      /** Domain */
      domain: string;
      /** Geometry */
      geometry: {
        [key: string]: unknown;
      };
      /**
       * Install Date
       * @default null
       */
      install_date: string | null;
      /**
       * Length M
       * @default null
       */
      length_m: number | string | null;
      /**
       * Manufacturer
       * @default null
       */
      manufacturer: string | null;
      /**
       * Material
       * @default null
       */
      material: string | null;
      /**
       * Model
       * @default null
       */
      model: string | null;
      /**
       * Notes
       * @default null
       */
      notes: string | null;
      /**
       * Serial Number
       * @default null
       */
      serial_number: string | null;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Warranty Until
       * @default null
       */
      warranty_until: string | null;
    };
    /** AssetUpdate */
    AssetUpdate: {
      /**
       * Attrs
       * @default null
       */
      attrs: {
        [key: string]: unknown;
      } | null;
      /**
       * Condition
       * @default null
       */
      condition: number | null;
      /**
       * Criticality
       * @default null
       */
      criticality: number | null;
      /**
       * Decommission Date
       * @default null
       */
      decommission_date: string | null;
      /**
       * Depth M
       * @default null
       */
      depth_m: number | string | null;
      /**
       * Diameter Mm
       * @default null
       */
      diameter_mm: number | null;
      /**
       * Geometry
       * @default null
       */
      geometry:
        | (
            | components["schemas"]["Point"]
            | components["schemas"]["LineString"]
            | components["schemas"]["Polygon"]
          )
        | null;
      /**
       * Install Date
       * @default null
       */
      install_date: string | null;
      /**
       * Length M
       * @default null
       */
      length_m: number | string | null;
      /**
       * Manufacturer
       * @default null
       */
      manufacturer: string | null;
      /**
       * Material
       * @default null
       */
      material: string | null;
      /**
       * Model
       * @default null
       */
      model: string | null;
      /**
       * Notes
       * @default null
       */
      notes: string | null;
      /**
       * Serial Number
       * @default null
       */
      serial_number: string | null;
      /**
       * Status
       * @default null
       */
      status: ("active" | "abandoned" | "removed" | "proposed") | null;
      /**
       * Warranty Until
       * @default null
       */
      warranty_until: string | null;
    };
    /**
     * LineString
     * @description LineString Model
     */
    LineString: {
      /**
       * Bbox
       * @default null
       */
      bbox:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /** Coordinates */
      coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "LineString";
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Tenant Slug */
      tenant_slug: string;
    };
    /** PasswordChangeRequest */
    PasswordChangeRequest: {
      /** Current */
      current: string;
      /** New */
      new: string;
    };
    /**
     * Point
     * @description Point Model
     */
    Point: {
      /**
       * Bbox
       * @default null
       */
      bbox:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /** Coordinates */
      coordinates: components["schemas"]["Position2D"] | components["schemas"]["Position3D"];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "Point";
    };
    /**
     * Polygon
     * @description Polygon Model
     */
    Polygon: {
      /**
       * Bbox
       * @default null
       */
      bbox:
        | [number, number, number, number]
        | [number, number, number, number, number, number]
        | null;
      /** Coordinates */
      coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "Polygon";
    };
    Position2D: [number, number];
    Position3D: [number, number, number];
    /** RegisterTenantRequest */
    RegisterTenantRequest: {
      /**
       * Admin Email
       * Format: email
       */
      admin_email: string;
      /** Admin Password */
      admin_password: string;
      /** Full Name */
      full_name: string;
      /**
       * Phone
       * @default null
       */
      phone: string | null;
      /** Slug */
      slug: string;
      /** Tenant Name */
      tenant_name: string;
    };
    /** RoleRead */
    RoleRead: {
      /** Code */
      code: string;
      /** Name */
      name: string;
    };
    /** TenantRead */
    TenantRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Settings */
      settings: {
        [key: string]: unknown;
      };
      /** Slug */
      slug: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TenantUpdate */
    TenantUpdate: {
      /**
       * Name
       * @default null
       */
      name: string | null;
      /**
       * Settings
       * @default null
       */
      settings: {
        [key: string]: unknown;
      } | null;
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Full Name */
      full_name: string;
      /** Password */
      password: string;
      /**
       * Phone
       * @default null
       */
      phone: string | null;
      /**
       * Role Codes
       * @default []
       */
      role_codes: string[];
    };
    /** UserListResponse */
    UserListResponse: {
      /** Items */
      items: components["schemas"]["UserRead"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** UserRead */
    UserRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Full Name */
      full_name: string;
      /** Is Active */
      is_active: boolean;
      /**
       * Last Login At
       * @default null
       */
      last_login_at: string | null;
      /**
       * Phone
       * @default null
       */
      phone: string | null;
      /**
       * Roles
       * @default []
       */
      roles: components["schemas"]["RoleRead"][];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** User Uid */
      user_uid: string;
    };
    /** UserRolesUpdate */
    UserRolesUpdate: {
      /** Role Codes */
      role_codes: string[];
    };
    /** UserUpdate */
    UserUpdate: {
      /**
       * Full Name
       * @default null
       */
      full_name: string | null;
      /**
       * Is Active
       * @default null
       */
      is_active: boolean | null;
      /**
       * Phone
       * @default null
       */
      phone: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
