"""``flask simulate-year`` — emit 12 months of synthetic operational data.

Domain model the simulator targets:

- A **work order** is an investigator's daily assignment for one
  *system* (water / sewer / storm) — eg "Hydrant flushing — north
  district, Tuesday". The WO carries the day's *activity* task
  (``WAT-TASK-HYDRANT-FLUSH``, ``WAT-TASK-VALVE-EXERCISE``,
  ``SEW-TASK-LIFT-STATION``, etc.) and accumulates ``task_data`` as the
  operator works through the day.
- A **service request** is a citizen-reported issue (discoloured water,
  sewer backup, low pressure, …). It carries the *citizen-issue* task
  (``WAT-TASK-DISCOLOURED``, ``SEW-TASK-BACKUP``, ``WAT-TASK-LOW-PRESSURE``)
  with its own form / chips / completion contract.
- **SRs roll up under the day's WO for their system.** When a citizen
  reports something, the SR gets attached to whichever daily WO of the
  matching domain is closest to its reported_at date, via
  ``service_request.work_order_id`` (existing FK).

Idempotent: rows generated by this command are tagged with
``attrs.simulated = True``. Re-running with ``--force`` wipes those
rows before regenerating. Deterministic: a single ``random.Random``
seed drives every random choice.
"""

from __future__ import annotations

import random
from datetime import UTC, date, datetime, time, timedelta
from decimal import Decimal
from typing import Any

import click
from flask import Flask
from flask.cli import with_appcontext
from sqlalchemy import select

from app.extensions import db
from app.models import (
    Asset,
    Comment,
    Crew,
    EntityLink,
    Inspection,
    ServiceRequest,
    TaskDefinition,
    Tenant,
    User,
    WorkOrder,
    WorkOrderTimeLog,
)

DEMO_SLUG = "demo"

# ---------------------------------------------------------------------------
# Daily-WO recipes (per system)
# ---------------------------------------------------------------------------

# Each entry: (task_code, wo_category, wo_title_template, weight).
# Weight controls how often the task fires on a given day for that system.
WATER_DAILY: list[tuple[str, str, str, int]] = [
    ("WAT-TASK-HYDRANT-FLUSH", "flushing", "Hydrant flushing — {district}", 4),
    ("WAT-TASK-VALVE-EXERCISE", "valve_exercise", "Valve exercising — {district}", 3),
    ("WAT-TASK-HYDRANT-FLOW", "inspection", "Hydrant flow testing — {district}", 1),
]
SEWER_DAILY: list[tuple[str, str, str, int]] = [
    ("SEW-TASK-LIFT-STATION", "inspection", "Lift station rounds — {district}", 4),
    ("SEW-TASK-MANHOLE-INSPECT", "inspection", "Manhole inspections — {district}", 2),
    ("SEW-TASK-CCTV", "inspection", "CCTV survey — {district}", 1),
]
STORM_DAILY: list[tuple[str, str, str, int]] = [
    ("STM-TASK-CB-INSPECT", "inspection", "Catch basin inspections — {district}", 3),
    ("STM-TASK-CB-CLOGGED", "cleaning", "CB cleaning route — {district}", 2),
    ("STM-TASK-DITCH-CLEAN", "cleaning", "Ditch / swale clearing — {district}", 1),
]

DAILY_BY_DOMAIN = {
    "water": WATER_DAILY,
    "sewer": SEWER_DAILY,
    "storm": STORM_DAILY,
}

DISTRICTS = ["North", "South", "East", "West", "Central"]


# Daily-activity task data presets, keyed by task code. Used to populate
# wo.task_data for completed daily WOs.
WO_TASK_DATA_PRESETS: dict[str, list[dict[str, Any]]] = {
    "WAT-TASK-HYDRANT-FLUSH": [
        {"flush_completed": True, "data_recorded": True,
         "flush_minutes": 8, "water_quality_improved": True},
        {"flush_completed": True, "data_recorded": True,
         "flush_minutes": 12, "water_quality_improved": True},
    ],
    "WAT-TASK-VALVE-EXERCISE": [
        {"valve_exercised": True, "data_recorded": True, "lubricated": True,
         "valve_condition": "normal", "turns": 14},
        {"valve_exercised": True, "data_recorded": True, "lubricated": True,
         "valve_condition": "stiff", "turns": 10},
    ],
    "WAT-TASK-HYDRANT-FLOW": [
        {"static_pressure_recorded": True, "flow_test_completed": True,
         "calculations_complete": True, "flow_gpm": 1240,
         "residual_psi": 48, "color_class": "blue"},
        {"static_pressure_recorded": True, "flow_test_completed": True,
         "calculations_complete": True, "flow_gpm": 880,
         "residual_psi": 35, "color_class": "green"},
    ],
    "SEW-TASK-LIFT-STATION": [
        {"wet_well_checked": True, "data_recorded": True, "generator_tested": True,
         "no_issues": True, "wet_well_level_normal": True, "pumps_ok": True,
         "wet_well_level_m": 1.8, "pump1_runtime_h": 124.5,
         "pump2_runtime_h": 119.2},
    ],
    "SEW-TASK-MANHOLE-INSPECT": [
        {"manhole_inspected": True, "data_recorded": True, "h2s_checked": True,
         "overall_condition": 2, "frame_condition": "good",
         "chimney_condition": "good", "bench_condition": "good"},
    ],
    "SEW-TASK-CCTV": [
        {"survey_completed": True, "ratings_complete": True,
         "recommendations_complete": True, "structural_total": 4,
         "om_total": 3, "length_surveyed_m": 145},
    ],
    "STM-TASK-CB-INSPECT": [
        {"sediment_measured": True, "structure_inspected": True,
         "sediment_depth_m": 0.10, "grate_good": True},
        {"sediment_measured": True, "structure_inspected": True,
         "sediment_depth_m": 0.28, "needs_cleaning": True},
    ],
    "STM-TASK-CB-CLOGGED": [
        {"basin_cleared": True, "outlet_checked": True, "drainage_restored": True,
         "sediment_volume": "1/3 truckload", "sediment_depth_m": 0.18},
    ],
    "STM-TASK-DITCH-CLEAN": [
        {"ditch_cleaned": True, "flow_path_clear": True, "length_cleaned_m": 75},
    ],
}


# ---------------------------------------------------------------------------
# Citizen SR distribution
# ---------------------------------------------------------------------------

# (category, domain, weight, default priority).
SR_MIX: list[tuple[str, str, int, str]] = [
    ("low_pressure", "water", 12, "normal"),
    ("no_water", "water", 8, "high"),
    ("discoloured_water", "water", 14, "normal"),
    ("water_quality", "water", 4, "normal"),
    ("damaged_asset", "water", 3, "high"),
    ("sewer_backup", "sewer", 10, "high"),
    ("odour", "sewer", 6, "normal"),
    ("flooding", "storm", 8, "high"),
    ("other", "water", 5, "normal"),
]

# SR category → citizen-issue task definition the SR carries.
SR_CATEGORY_TASK = {
    "low_pressure": "WAT-TASK-LOW-PRESSURE",
    "no_water": "WAT-TASK-NO-WATER",
    "discoloured_water": "WAT-TASK-DISCOLOURED",
    "water_quality": "WAT-TASK-DISCOLOURED",
    "damaged_asset": "WAT-TASK-HYDRANT-HIT",
    "sewer_backup": "SEW-TASK-BACKUP",
    "odour": "SEW-TASK-ODOR",
    "flooding": "STM-TASK-CB-CLOGGED",
}

# Citizen-issue task data presets — applied to the SR's task_data when
# the SR is "resolved", so the smart-comment chips render against real
# values. Empty SRs stay open (no task_data).
SR_TASK_DATA_PRESETS: dict[str, list[dict[str, Any]]] = {
    "WAT-TASK-DISCOLOURED": [
        {"site_visited": True, "cold_run_minutes": 10, "cold_outcome": "cleared",
         "chlorine_residual": 0.18, "outcome": "resolved_on_site",
         "likely_cause": "hydrant_use"},
        {"site_visited": True, "cold_run_minutes": 12, "cold_outcome": "still_discoloured",
         "flush_minutes": 6, "chlorine_residual": 0.22, "outcome": "resolved_on_site",
         "likely_cause": "recent_main_work"},
        {"site_visited": True, "cold_run_minutes": 8, "cold_outcome": "cleared",
         "chlorine_residual": 0.14, "likely_cause": "internal_plumbing",
         "outcome": "referred_internal_plumbing"},
    ],
    "WAT-TASK-LOW-PRESSURE": [
        {"area_checked": True, "pressure_tested": True, "valve_position": "partially_closed",
         "valve_location": "Birch & 7th", "outcome": "resolved_on_site"},
    ],
    "WAT-TASK-NO-WATER": [
        {"area_checked": True, "valves_checked": True, "valve_closed": True,
         "valve_location": "Cedar & 3rd", "outcome": "resolved_on_site"},
    ],
    "WAT-TASK-HYDRANT-HIT": [
        {"damage_assessed": True, "hydrant_status": "knocked_over",
         "hydrant_repaired": True, "flow_tested": True},
    ],
    "SEW-TASK-BACKUP": [
        {"site_assessed": True, "blockage_cleared": True, "flow_restored": True,
         "documentation_complete": True, "backup_cleared": True,
         "likely_cause": "grease"},
    ],
    "SEW-TASK-ODOR": [
        {"source_located": True, "area_inspected": True,
         "likely_cause": "dry_trap", "outcome": "advised_customer"},
    ],
    "STM-TASK-CB-CLOGGED": [
        {"basin_cleared": True, "outlet_checked": True, "drainage_restored": True,
         "sediment_volume": "1/3 truckload", "sediment_depth_m": 0.18},
    ],
}

INSPECTION_MIX: list[tuple[str, int]] = [
    ("hydrant_flow", 4),
    ("valve_exercise", 6),
    ("manhole", 3),
    ("catch_basin", 8),
    ("lift_station_round", 5),
    ("cctv", 2),
]
INSPECTION_CLASS_HINT = {
    "hydrant_flow": "WAT_HYD",
    "valve_exercise": "WAT_VLV",
    "manhole": "SAN_MH",
    "catch_basin": "STM_CB",
    "lift_station_round": "SAN_LFT",
    "cctv": "SAN_MAIN",
}


SR_DESCRIPTIONS = {
    "low_pressure": [
        "Resident reports pressure dropped overnight.",
        "Multiple complaints of weak flow at kitchen tap.",
    ],
    "no_water": [
        "No water at any tap. Confirmed neighbours unaffected.",
    ],
    "discoloured_water": [
        "Brown water from cold tap. Customer rinsing now.",
        "Yellow tinge after running water 5 minutes.",
        "Discolouration following work crews on the street.",
    ],
    "water_quality": [
        "Customer reports unusual chlorine smell.",
    ],
    "damaged_asset": [
        "Vehicle struck a hydrant on Main near Oak.",
    ],
    "sewer_backup": [
        "Sewage backing up into basement laundry tub.",
        "Slow drain progressed to backup overnight.",
    ],
    "odour": [
        "Strong sewer smell near manhole at 4th & Cedar.",
    ],
    "flooding": [
        "Water pooling at intersection — catch basin clogged with leaves.",
    ],
    "other": [
        "Customer concerned about discoloured curb stop cover.",
    ],
}

CALLER_NAMES = [
    "Jane Doe", "Marcus Lee", "Priya Patel", "Sam Cohen", "Elena Park",
    "Diane Wright", "Tom Nguyen", "Rachel Kim", "Karim Adebayo", "Lila Rossi",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _weighted_choice(rng: random.Random, choices: list[tuple[Any, int]]) -> Any:
    total = sum(w for _, w in choices)
    pick = rng.uniform(0, total)
    upto = 0.0
    for value, w in choices:
        upto += w
        if upto >= pick:
            return value
    return choices[-1][0]


def _label_simulated(payload: dict[str, Any]) -> dict[str, Any]:
    return {**payload, "simulated": True}


def _next_number(session, model, column, taken: set[str], prefix: str, start: int) -> str:
    n = start
    while True:
        candidate = f"{prefix}{n}"
        if candidate not in taken:
            existing = session.scalar(select(column).where(column == candidate))
            if existing is None:
                taken.add(candidate)
                return candidate
        n += 1


def _is_workday(d: date) -> bool:
    return d.weekday() < 5  # Mon-Fri


def _random_business_dt(rng: random.Random, base_day: date) -> datetime:
    hour = rng.choices(
        population=list(range(7, 18)),
        weights=[3, 6, 9, 10, 10, 8, 8, 9, 7, 5, 3],
    )[0]
    return datetime.combine(
        base_day,
        time(hour=hour, minute=rng.randint(0, 59), second=rng.randint(0, 59)),
        tzinfo=UTC,
    )


# ---------------------------------------------------------------------------
# Wipe (only simulated rows)
# ---------------------------------------------------------------------------


def _wipe_simulated(tenant_id: int) -> None:
    db.session.execute(
        Comment.__table__.delete().where(
            Comment.tenant_id == tenant_id,
            Comment.body.like("[sim]%"),
        )
    )
    db.session.execute(
        EntityLink.__table__.delete().where(
            EntityLink.tenant_id == tenant_id,
            EntityLink.note.like("[sim]%"),
        )
    )
    db.session.execute(
        WorkOrderTimeLog.__table__.delete().where(
            WorkOrderTimeLog.work_order_id.in_(
                select(WorkOrder.id).where(
                    WorkOrder.tenant_id == tenant_id,
                    WorkOrder.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
                )
            )
        )
    )
    # Detach simulated SRs from any WO before deleting WOs (FK is SET NULL,
    # but doing this explicitly keeps the order obvious).
    db.session.execute(
        Inspection.__table__.delete().where(
            Inspection.tenant_id == tenant_id,
            Inspection.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
        )
    )
    db.session.execute(
        ServiceRequest.__table__.delete().where(
            ServiceRequest.tenant_id == tenant_id,
            ServiceRequest.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
        )
    )
    db.session.execute(
        WorkOrder.__table__.delete().where(
            WorkOrder.tenant_id == tenant_id,
            WorkOrder.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
        )
    )
    db.session.commit()


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def _simulate(tenant: Tenant, *, seed: int, today: datetime) -> dict[str, int]:
    rng = random.Random(seed)
    counts = {"daily_wo": 0, "sr": 0, "sr_attached": 0, "inspection": 0,
              "comment": 0, "time_log": 0}

    users = db.session.execute(
        select(User).where(User.tenant_id == tenant.id)
    ).scalars().all()
    if not users:
        raise click.UsageError("Tenant has no users — seed-demo first")
    operators = [
        u for u in users
        if "tech" in (u.email or "") or "supervisor" in (u.email or "")
    ]
    if not operators:
        operators = users
    intake = next((u for u in users if "intake" in (u.email or "")), users[0])

    crews = db.session.execute(
        select(Crew).where(Crew.tenant_id == tenant.id)
    ).scalars().all()

    assets = db.session.execute(
        select(Asset).where(Asset.tenant_id == tenant.id)
    ).scalars().all()
    assets_by_class: dict[str, list[Asset]] = {}
    for a in assets:
        assets_by_class.setdefault(a.class_code, []).append(a)

    tasks = db.session.execute(
        select(TaskDefinition).where(
            TaskDefinition.tenant_id == tenant.id,
            TaskDefinition.status == "active",
        )
    ).scalars().all()
    tasks_by_code = {t.code: t for t in tasks}

    sr_taken: set[str] = set()
    wo_taken: set[str] = set()
    insp_taken: set[str] = set()

    domain_assets = {
        "water": assets_by_class.get("WAT_HYD", [])
                 + assets_by_class.get("WAT_MAIN", [])
                 + assets_by_class.get("WAT_VLV", [])
                 + assets_by_class.get("WAT_SVC", []),
        "sewer": assets_by_class.get("SAN_MAIN", [])
                 + assets_by_class.get("SAN_MH", [])
                 + assets_by_class.get("SAN_LFT", []),
        "storm": assets_by_class.get("STM_CB", [])
                 + assets_by_class.get("STM_MAIN", []),
    }
    for k, v in list(domain_assets.items()):
        if not v:
            domain_assets[k] = assets

    start_day = (today - timedelta(days=365)).date()
    end_day = today.date()

    # ---- Daily WOs: one per (system, workday) per active operator chunk ----
    # Realistic-ish density: each system gets a WO ~3-5 weekdays/week.
    daily_wos: list[WorkOrder] = []
    daily_wos_by_domain_date: dict[tuple[str, date], list[WorkOrder]] = {}
    cursor = start_day
    while cursor <= end_day:
        if _is_workday(cursor):
            for domain in ("water", "sewer", "storm"):
                # Each system has ~70% chance of a daily WO on any weekday.
                if rng.random() > 0.70:
                    continue
                recipe = _weighted_choice(
                    rng,
                    [(r, r[3]) for r in DAILY_BY_DOMAIN[domain]],
                )
                task_code, category, title_tpl, _w = recipe
                task = tasks_by_code.get(task_code)
                district = rng.choice(DISTRICTS)
                operator = rng.choice(operators)
                crew = rng.choice(crews) if crews and rng.random() < 0.4 else None
                scheduled = _random_business_dt(rng, cursor)

                # Status: most are completed (in the past), today's are
                # in_progress / open, future days are open.
                if cursor < end_day - timedelta(days=2):
                    final = rng.choices(
                        ["completed", "completed", "completed", "completed",
                         "cancelled"],
                        k=1,
                    )[0]
                elif cursor < end_day:
                    final = rng.choices(
                        ["completed", "in_progress", "open"], weights=[5, 3, 2],
                    )[0]
                else:
                    final = rng.choices(
                        ["assigned", "open", "in_progress"], weights=[4, 3, 2],
                    )[0]

                started_at = None
                completed_at = None
                if final in {"in_progress", "completed", "cancelled"}:
                    started_at = scheduled + timedelta(hours=rng.randint(0, 2))
                if final == "completed":
                    completed_at = started_at + timedelta(
                        hours=rng.randint(2, 7)
                    )
                    if completed_at > today:
                        completed_at = today - timedelta(hours=1)

                task_data: dict[str, Any] = {}
                if task and final == "completed" and task_code in WO_TASK_DATA_PRESETS:
                    task_data = dict(rng.choice(WO_TASK_DATA_PRESETS[task_code]))

                wo = WorkOrder(
                    tenant_id=tenant.id,
                    wo_number=_next_number(
                        db.session, WorkOrder, WorkOrder.wo_number,
                        wo_taken, "WO-", 200000,
                    ),
                    type="planned",
                    category=category,
                    priority="normal",
                    status=final,
                    title=title_tpl.format(district=district),
                    description=f"[sim] Daily {domain} crew assignment — {district} district.",
                    scheduled_for=scheduled,
                    started_at=started_at,
                    completed_at=completed_at,
                    assigned_to=operator.id if final not in {"draft"} else None,
                    crew_id=crew.id if crew else None,
                    task_definition_id=task.id if task else None,
                    task_data=task_data,
                    attrs=_label_simulated({
                        "domain": domain,
                        "district": district,
                        "daily": True,
                    }),
                )
                db.session.add(wo)
                db.session.flush()
                daily_wos.append(wo)
                daily_wos_by_domain_date.setdefault((domain, cursor), []).append(wo)
                counts["daily_wo"] += 1

                # Time logs on completed / in_progress daily WOs.
                if final in {"completed", "in_progress"} and started_at:
                    n_logs = rng.choices([2, 3, 4], weights=[3, 5, 2])[0]
                    log_cursor = started_at
                    end_cap = completed_at or (started_at + timedelta(hours=6))
                    for _ in range(n_logs):
                        seg = rng.choice([0.75, 1.0, 1.5, 2.0])
                        seg_end = min(log_cursor + timedelta(hours=seg), end_cap)
                        if seg_end <= log_cursor:
                            break
                        db.session.add(WorkOrderTimeLog(
                            work_order_id=wo.id,
                            user_id=operator.id,
                            started_at=log_cursor,
                            ended_at=seg_end,
                            hours_decimal=Decimal(
                                f"{(seg_end - log_cursor).total_seconds() / 3600:.2f}"
                            ),
                            notes=f"[sim] {rng.choice(['Travel', 'On site', 'Documenting'])}",
                        ))
                        counts["time_log"] += 1
                        log_cursor = seg_end + timedelta(minutes=rng.randint(0, 30))
                        if log_cursor >= end_cap:
                            break

                # Operator wrap-up comments on completed WOs.
                if final == "completed":
                    for _ in range(rng.choices([1, 2], weights=[6, 4])[0]):
                        db.session.add(Comment(
                            tenant_id=tenant.id,
                            entity_type="work_order",
                            entity_id=wo.id,
                            body=f"[sim] {rng.choice(['Route complete.', 'No issues found on route.', 'All assignments closed for the day.'])}",
                            created_by=operator.id,
                            created_at=(completed_at or scheduled),
                        ))
                        counts["comment"] += 1
        cursor += timedelta(days=1)

    db.session.flush()

    # ---- Citizen SRs ----
    target_srs = 200
    for i in range(target_srs):
        day_offset = rng.randint(0, 364)
        when = _random_business_dt(rng, start_day + timedelta(days=day_offset))
        category, domain, base_w, priority = rng.choice(SR_MIX)
        candidates = domain_assets.get(domain) or assets
        asset = rng.choice(candidates) if candidates else None
        sr_task_code = SR_CATEGORY_TASK.get(category)
        sr_task = tasks_by_code.get(sr_task_code) if sr_task_code else None

        # Decide lifecycle outcome.
        roll = rng.random()
        if roll < 0.65:
            sr_status = "dispatched"  # rolled into a daily WO
        elif roll < 0.78:
            sr_status = "closed"
        elif roll < 0.86:
            sr_status = "duplicate"
        elif roll < 0.93:
            sr_status = "triaged"
        else:
            sr_status = "new"

        # Populate task_data when the SR has been worked.
        sr_task_data: dict[str, Any] = {}
        if (sr_status in {"dispatched", "closed"}
                and sr_task_code
                and sr_task_code in SR_TASK_DATA_PRESETS):
            sr_task_data = dict(rng.choice(SR_TASK_DATA_PRESETS[sr_task_code]))

        sr = ServiceRequest(
            tenant_id=tenant.id,
            sr_number=_next_number(
                db.session, ServiceRequest, ServiceRequest.sr_number,
                sr_taken, "SR-", 100000,
            ),
            category=category,
            domain=domain,
            priority=priority,
            status=sr_status,
            reported_at=when,
            caller_name=rng.choice(CALLER_NAMES),
            caller_phone=f"555-{rng.randint(1000, 9999)}",
            reported_address=getattr(asset, "address_cached", None)
                or f"{rng.randint(10, 9999)} Main St",
            asset_id=asset.id if asset else None,
            description=rng.choice(
                SR_DESCRIPTIONS.get(category, ["Reported issue."])
            ),
            intake_user_id=intake.id,
            task_definition_id=sr_task.id if sr_task else None,
            task_data=sr_task_data,
            closed_at=(when + timedelta(hours=rng.randint(2, 48)))
                if sr_status in {"closed", "duplicate"} else None,
            closure_reason=("resolved" if sr_status == "closed"
                            else "duplicate" if sr_status == "duplicate"
                            else None),
            attrs=_label_simulated({}),
        )
        db.session.add(sr)
        db.session.flush()
        counts["sr"] += 1

        # Attach to the day's WO for this domain (or the closest workday's
        # WO) — only meaningful for SRs that were worked.
        if sr_status in {"dispatched", "closed"}:
            attached = _attach_sr_to_daily_wo(
                rng=rng,
                tenant_id=tenant.id,
                sr=sr,
                domain=domain,
                reported_on=when.date(),
                daily_wos_by_domain_date=daily_wos_by_domain_date,
                intake_user_id=intake.id,
            )
            if attached:
                counts["sr_attached"] += 1

        # Light comments on a fraction of SRs.
        for _ in range(rng.choices([0, 1, 2], weights=[55, 32, 13])[0]):
            db.session.add(Comment(
                tenant_id=tenant.id,
                entity_type="service_request",
                entity_id=sr.id,
                body=f"[sim] {rng.choice(['Customer called back to confirm details.', 'Spoke with neighbour — same issue reported.', 'Left voicemail with caller.'])}",
                created_by=intake.id,
                created_at=when + timedelta(hours=rng.randint(1, 48)),
            ))
            counts["comment"] += 1

        if i % 25 == 0:
            db.session.flush()

    # ---- Inspections (independent of WO/SR lifecycle) ----
    target_inspections = 280
    for i in range(target_inspections):
        day_offset = rng.randint(0, 364)
        when = _random_business_dt(rng, start_day + timedelta(days=day_offset))
        kind = _weighted_choice(rng, INSPECTION_MIX)
        hint = INSPECTION_CLASS_HINT[kind]
        candidates = assets_by_class.get(hint) or assets
        asset = rng.choice(candidates) if candidates else None
        operator = rng.choice(operators)
        condition = rng.randint(1, 5)
        ins = Inspection(
            tenant_id=tenant.id,
            inspection_number=_next_number(
                db.session, Inspection, Inspection.inspection_number,
                insp_taken, "INS-", 300000,
            ),
            kind=kind,
            asset_id=asset.id if asset else None,
            performed_at=when,
            performed_by=operator.id,
            overall_condition=condition,
            pass_=condition <= 3,
            notes=rng.choice([
                "[sim] Routine inspection. No issues.",
                "[sim] Sediment level above threshold — schedule cleaning.",
                "[sim] All measurements within tolerance.",
            ]),
            data={"simulated": True},
            attrs=_label_simulated({}),
        )
        db.session.add(ins)
        counts["inspection"] += 1
        if i % 50 == 0:
            db.session.flush()

    db.session.commit()
    return counts


def _attach_sr_to_daily_wo(
    *,
    rng: random.Random,
    tenant_id: int,
    sr: ServiceRequest,
    domain: str,
    reported_on: date,
    daily_wos_by_domain_date: dict[tuple[str, date], list[WorkOrder]],
    intake_user_id: int,
) -> bool:
    """Attach an SR to the day's WO for its system. If no WO exists on the
    exact day, walks forward up to 5 weekdays to find one."""
    candidate_dates = [reported_on + timedelta(days=offset) for offset in range(0, 6)]
    for candidate in candidate_dates:
        wos = daily_wos_by_domain_date.get((domain, candidate))
        if not wos:
            continue
        wo = rng.choice(wos)
        sr.work_order_id = wo.id
        db.session.add(EntityLink(
            tenant_id=tenant_id,
            source_type="service_request",
            source_id=sr.id,
            target_type="work_order",
            target_id=wo.id,
            kind="caused_by",
            note=f"[sim] rolled into daily {domain} WO",
            created_by=intake_user_id,
        ))
        return True
    return False


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def register(app: Flask) -> None:
    @app.cli.command("simulate-year")
    @click.option("--tenant", "tenant_slug", default=DEMO_SLUG, show_default=True)
    @click.option("--seed", type=int, default=42, show_default=True)
    @click.option("--force", is_flag=True, help="Wipe simulated rows first.")
    @with_appcontext
    def simulate_year(tenant_slug: str, seed: int, force: bool):
        tenant = db.session.scalar(
            select(Tenant)
            .where(Tenant.slug == tenant_slug)
            .execution_options(skip_tenant_filter=True)
        )
        if tenant is None:
            raise click.UsageError(f"Tenant {tenant_slug!r} not found")

        already = db.session.scalar(
            select(WorkOrder.id).where(
                WorkOrder.tenant_id == tenant.id,
                WorkOrder.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
            ).limit(1)
        )
        if already and not force:
            raise click.UsageError(
                "Tenant already has simulated rows. Re-run with --force to wipe them."
            )
        if force:
            click.echo("Wiping previous simulation…")
            _wipe_simulated(tenant.id)

        click.echo(f"Simulating 12 months of work for {tenant_slug!r} (seed={seed})…")
        today = datetime.now(UTC)
        counts = _simulate(tenant, seed=seed, today=today)
        click.echo("\n".join([
            "",
            "Done.",
            f"  Daily work orders (per system per workday) : {counts['daily_wo']}",
            f"  Service requests                           : {counts['sr']}",
            f"    of which rolled into a daily WO          : {counts['sr_attached']}",
            f"  Inspections                                : {counts['inspection']}",
            f"  Time logs                                  : {counts['time_log']}",
            f"  Comments                                   : {counts['comment']}",
        ]))
