"""``flask simulate-year`` — emit 12 months of synthetic operational data.

Picks up the demo tenant's existing baseline (users, crews, assets,
task definitions, schedules) and lays a realistic year of activity on
top: service requests with full intake → dispatch → close lifecycles,
work orders progressing through every status with task definitions,
task_data, time logs, and operator comments, inspections of every
kind, and entity links wiring the dispatched SRs to their WOs.

Idempotent: rows generated by this command are tagged with
``attrs.simulated = True``. Re-running with ``--force`` wipes those
rows before regenerating; without ``--force`` it refuses to run if any
simulated rows already exist for the tenant.

Deterministic: a single ``random.Random`` seed drives every random
choice so the same inputs reliably produce the same data.
"""

from __future__ import annotations

import random
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from typing import Any

import click
from flask import Flask
from flask.cli import with_appcontext
from sqlalchemy import select

from app.extensions import db
from app.models import (
    Asset,
    Comment,
    Crew,
    EntityLink,
    Inspection,
    ServiceRequest,
    TaskDefinition,
    Tenant,
    User,
    WorkOrder,
    WorkOrderTimeLog,
)

DEMO_SLUG = "demo"

# ---------------------------------------------------------------------------
# Distributions
# ---------------------------------------------------------------------------

# (category, domain, weight, default priority).  Only categories valid in
# the current SR enum — extending it is a separate PR.
SR_MIX: list[tuple[str, str, int, str]] = [
    ("low_pressure", "water", 12, "normal"),
    ("no_water", "water", 8, "high"),
    ("discoloured_water", "water", 14, "normal"),
    ("water_quality", "water", 4, "normal"),
    ("damaged_asset", "water", 3, "high"),
    ("sewer_backup", "sewer", 10, "high"),
    ("odour", "sewer", 6, "normal"),
    ("flooding", "storm", 8, "high"),
    ("other", "water", 5, "normal"),
]

# Maps SR category → preferred task definition code.  Falls back to
# manual / no task if the code isn't seeded.
SR_CATEGORY_TASK = {
    "low_pressure": "WAT-TASK-LOW-PRESSURE",
    "no_water": "WAT-TASK-NO-WATER",
    "discoloured_water": "WAT-TASK-DISCOLOURED",
    "water_quality": "WAT-TASK-DISCOLOURED",
    "damaged_asset": "WAT-TASK-HYDRANT-HIT",
    "sewer_backup": "SEW-TASK-BACKUP",
    "odour": "SEW-TASK-ODOR",
    "flooding": "STM-TASK-CB-CLOGGED",
}

# Realistic completion data per task code, keyed off form fields the
# task expects.  Used to fill the WO's task_data so smart-comment
# conditions actually match.
TASK_DATA_PRESETS: dict[str, list[dict[str, Any]]] = {
    "WAT-TASK-DISCOLOURED": [
        {"site_visited": True, "cold_run_minutes": 10, "cold_outcome": "cleared",
         "chlorine_residual": 0.18, "outcome": "resolved_on_site",
         "likely_cause": "hydrant_use"},
        {"site_visited": True, "cold_run_minutes": 12, "cold_outcome": "still_discoloured",
         "flush_minutes": 6, "chlorine_residual": 0.22, "outcome": "resolved_on_site",
         "likely_cause": "recent_main_work"},
        {"site_visited": True, "cold_run_minutes": 8, "cold_outcome": "cleared",
         "chlorine_residual": 0.14, "likely_cause": "internal_plumbing",
         "outcome": "referred_internal_plumbing"},
    ],
    "WAT-TASK-LOW-PRESSURE": [
        {"area_checked": True, "pressure_tested": True, "valve_position": "partially_closed",
         "valve_location": "Birch & 7th", "outcome": "resolved_on_site"},
        {"area_checked": True, "pressure_tested": True, "service_line_checked": True,
         "likely_cause": "service_line", "outcome": "referred_to_customer"},
    ],
    "WAT-TASK-NO-WATER": [
        {"area_checked": True, "valves_checked": True, "valve_closed": True,
         "valve_location": "Cedar & 3rd", "outcome": "resolved_on_site"},
        {"area_checked": True, "valves_checked": True, "main_break_found": True,
         "outcome": "main_break_dispatched"},
    ],
    "WAT-TASK-MAIN-BREAK": [
        {"valves_isolated": True, "valve_1": "V-1042", "valve_2": "V-1043",
         "customers_notified": True, "repair_completed": True, "service_restored": True},
    ],
    "WAT-TASK-HYDRANT-HIT": [
        {"damage_assessed": True, "hydrant_status": "knocked_over",
         "hydrant_repaired": True, "flow_tested": True},
        {"damage_assessed": True, "hydrant_status": "leaking",
         "damage_location": "bonnet flange", "hydrant_repaired": True, "flow_tested": True},
    ],
    "WAT-TASK-VALVE-EXERCISE": [
        {"valve_exercised": True, "data_recorded": True, "valve_condition": "normal",
         "turns": 14, "lubricated": True},
        {"valve_exercised": True, "data_recorded": True, "valve_condition": "stiff",
         "turns": 10, "lubricated": True},
    ],
    "WAT-TASK-HYDRANT-FLUSH": [
        {"flush_completed": True, "data_recorded": True, "flush_minutes": 8,
         "water_quality_improved": True},
    ],
    "WAT-TASK-HYDRANT-FLOW": [
        {"static_pressure_recorded": True, "flow_test_completed": True,
         "calculations_complete": True, "flow_gpm": 1240, "residual_psi": 48,
         "color_class": "blue"},
    ],
    "SEW-TASK-BACKUP": [
        {"site_assessed": True, "blockage_cleared": True, "flow_restored": True,
         "documentation_complete": True, "backup_cleared": True,
         "likely_cause": "grease"},
        {"site_assessed": True, "blockage_cleared": True, "flow_restored": True,
         "documentation_complete": True, "backup_cleared": True,
         "likely_cause": "main_line"},
    ],
    "SEW-TASK-ODOR": [
        {"source_located": True, "area_inspected": True,
         "likely_cause": "dry_trap", "outcome": "advised_customer"},
        {"source_located": True, "area_inspected": True,
         "likely_cause": "main_line", "outcome": "scheduled_cleaning"},
    ],
    "SEW-TASK-LIFT-STATION": [
        {"wet_well_checked": True, "data_recorded": True, "generator_tested": True,
         "no_issues": True, "wet_well_level_normal": True, "pumps_ok": True,
         "wet_well_level_m": 1.8, "pump1_runtime_h": 124.5, "pump2_runtime_h": 119.2},
    ],
    "STM-TASK-CB-CLOGGED": [
        {"basin_cleared": True, "outlet_checked": True, "drainage_restored": True,
         "sediment_volume": "1/3 truckload", "sediment_depth_m": 0.18},
        {"basin_cleared": True, "outlet_checked": True, "drainage_restored": True,
         "sediment_volume": "2/3 truckload", "sediment_depth_m": 0.34},
    ],
}


# Inspection kind weights — mirror typical operational rhythm.
INSPECTION_MIX: list[tuple[str, int]] = [
    ("hydrant_flow", 4),
    ("valve_exercise", 6),
    ("manhole", 3),
    ("catch_basin", 8),
    ("lift_station_round", 5),
    ("cctv", 2),
]

# Asset-class hint per inspection kind.  None means "any".
INSPECTION_CLASS_HINT = {
    "hydrant_flow": "WAT_HYD",
    "valve_exercise": "WAT_VLV",
    "manhole": "SAN_MH",
    "catch_basin": "STM_CB",
    "lift_station_round": "SAN_LFT",
    "cctv": "SAN_MAIN",
}


# Free-text snippets for SR descriptions, varying by category.
SR_DESCRIPTIONS = {
    "low_pressure": [
        "Resident reports pressure dropped overnight.",
        "Multiple complaints of weak flow at kitchen tap.",
        "Pressure drops when neighbour's irrigation runs.",
    ],
    "no_water": [
        "No water at any tap. Confirmed neighbours unaffected.",
        "Service stopped after morning use. Curb stop closed?",
    ],
    "discoloured_water": [
        "Brown water from cold tap. Customer rinsing now.",
        "Yellow tinge after running water 5 minutes.",
        "Discolouration following work crews on the street.",
    ],
    "water_quality": [
        "Customer reports unusual chlorine smell.",
        "Caller asking about cloudy water in tub.",
    ],
    "damaged_asset": [
        "Vehicle struck a hydrant on Main near Oak.",
        "Reported leak from hydrant cap.",
    ],
    "sewer_backup": [
        "Sewage backing up into basement laundry tub.",
        "Slow drain progressed to backup overnight.",
        "Customer reports gurgling and rising water in floor drain.",
    ],
    "odour": [
        "Strong sewer smell near manhole at 4th & Cedar.",
        "Persistent odour around the lift station.",
    ],
    "flooding": [
        "Water pooling at intersection — catch basin clogged with leaves.",
        "Storm runoff backing up onto driveway.",
    ],
    "other": [
        "Customer concerned about discoloured curb stop cover.",
        "Resident reports unusual sound near meter pit.",
    ],
}

CALLER_NAMES = [
    "Jane Doe", "Marcus Lee", "Priya Patel", "Sam Cohen", "Elena Park",
    "Diane Wright", "Tom Nguyen", "Rachel Kim", "Karim Adebayo", "Lila Rossi",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _weighted_choice(rng: random.Random, choices: list[tuple[Any, int, ...]]) -> tuple[Any, ...]:
    """Pick a row from a weighted-tuple list. Weight is the second element."""
    total = sum(c[1] for c in choices) if choices and len(choices[0]) >= 2 else 0
    pick = rng.uniform(0, total)
    upto = 0.0
    for c in choices:
        upto += c[1]
        if upto >= pick:
            return c
    return choices[-1]


def _pick_sr_mix(rng: random.Random, day_of_year: int) -> tuple[str, str, str]:
    """Pick (category, domain, priority).  Light seasonal bias."""
    weights = []
    for category, domain, base_w, prio in SR_MIX:
        w = base_w
        # Winter (day_of_year 0-90 / 335-365): more main-break complaints.
        if (day_of_year < 90 or day_of_year > 335) and category == "no_water":
            w *= 2
        # Summer (180-260): more discoloured-water during construction season.
        if 180 <= day_of_year <= 260 and category == "discoloured_water":
            w *= 1.7
        # Fall (260-335): more flooding (leaves clogging CBs).
        if 260 <= day_of_year <= 335 and category == "flooding":
            w *= 2.2
        weights.append((category, w, domain, prio))
    weighted = [(c[0], int(c[1] * 100), c[2], c[3]) for c in weights]
    pick = _weighted_choice(rng, [(c[0], c[1]) for c in weighted])
    chosen = next(c for c in weighted if c[0] == pick[0])
    return chosen[0], chosen[2], chosen[3]


def _pick_inspection_kind(rng: random.Random) -> str:
    pick = _weighted_choice(rng, INSPECTION_MIX)
    return pick[0]


def _random_business_dt(rng: random.Random, base_day: datetime) -> datetime:
    """Random datetime on `base_day` skewed toward business hours."""
    hour = rng.choices(
        population=list(range(24)),
        weights=[1, 1, 1, 1, 1, 2, 4, 6, 8, 10, 10, 9, 8, 8, 9, 8, 6, 4, 3, 2, 2, 2, 1, 1],
    )[0]
    minute = rng.randint(0, 59)
    return base_day.replace(hour=hour, minute=minute, second=rng.randint(0, 59), microsecond=0)


def _label_simulated(payload: dict[str, Any]) -> dict[str, Any]:
    return {**payload, "simulated": True}


def _maybe_pick_task(rng: random.Random, tasks_by_code: dict[str, TaskDefinition], category: str) -> TaskDefinition | None:
    code = SR_CATEGORY_TASK.get(category)
    if not code:
        return None
    return tasks_by_code.get(code)


def _next_sr_number(session, tenant_id: int, taken: set[str]) -> str:
    """Generate a unique SR number not colliding with existing or just-staged ones."""
    n = 100000
    while True:
        candidate = f"SR-{n}"
        if candidate not in taken:
            existing = session.scalar(
                select(ServiceRequest.id).where(
                    ServiceRequest.tenant_id == tenant_id,
                    ServiceRequest.sr_number == candidate,
                )
            )
            if existing is None:
                taken.add(candidate)
                return candidate
        n += 1


def _next_wo_number(session, tenant_id: int, taken: set[str]) -> str:
    n = 200000
    while True:
        candidate = f"WO-{n}"
        if candidate not in taken:
            existing = session.scalar(
                select(WorkOrder.id).where(
                    WorkOrder.tenant_id == tenant_id,
                    WorkOrder.wo_number == candidate,
                )
            )
            if existing is None:
                taken.add(candidate)
                return candidate
        n += 1


def _next_inspection_number(session, tenant_id: int, taken: set[str]) -> str:
    n = 300000
    while True:
        candidate = f"INS-{n}"
        if candidate not in taken:
            existing = session.scalar(
                select(Inspection.id).where(
                    Inspection.tenant_id == tenant_id,
                    Inspection.inspection_number == candidate,
                )
            )
            if existing is None:
                taken.add(candidate)
                return candidate
        n += 1


# ---------------------------------------------------------------------------
# Wipe (only simulated rows)
# ---------------------------------------------------------------------------


def _wipe_simulated(tenant_id: int) -> None:
    """Delete only rows tagged ``attrs.simulated = True``."""
    # Time logs: cascade via WorkOrder when WO is deleted.
    sim_filter = lambda model: db.session.execute(
        model.__table__.delete().where(
            model.tenant_id == tenant_id,
            model.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
        )
    )

    # Comments: tagged via attrs? Comment lacks attrs — use a body marker.
    db.session.execute(
        Comment.__table__.delete().where(
            Comment.tenant_id == tenant_id,
            Comment.body.like("[sim]%"),
        )
    )
    # Entity links: tagged via note marker.
    db.session.execute(
        EntityLink.__table__.delete().where(
            EntityLink.tenant_id == tenant_id,
            EntityLink.note.like("[sim]%"),
        )
    )

    # Time logs cascade via FK ondelete=CASCADE on WorkOrder.id.
    db.session.execute(
        WorkOrderTimeLog.__table__.delete().where(
            WorkOrderTimeLog.work_order_id.in_(
                select(WorkOrder.id).where(
                    WorkOrder.tenant_id == tenant_id,
                    WorkOrder.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
                )
            )
        )
    )

    sim_filter(Inspection)
    sim_filter(WorkOrder)
    sim_filter(ServiceRequest)
    db.session.commit()


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def _simulate(tenant: Tenant, *, seed: int, today: datetime) -> dict[str, int]:
    rng = random.Random(seed)
    counts = {"sr": 0, "wo": 0, "inspection": 0, "comment": 0, "time_log": 0, "link": 0}

    # Pull baseline rows once.
    users = db.session.execute(
        select(User).where(User.tenant_id == tenant.id)
    ).scalars().all()
    if not users:
        raise click.UsageError("Tenant has no users — seed-demo first")
    operators = [u for u in users if "tech" in (u.email or "") or "supervisor" in (u.email or "")]
    if not operators:
        operators = users
    intake = next((u for u in users if "intake" in (u.email or "")), users[0])

    crews = db.session.execute(
        select(Crew).where(Crew.tenant_id == tenant.id)
    ).scalars().all()

    assets = db.session.execute(
        select(Asset).where(Asset.tenant_id == tenant.id)
    ).scalars().all()
    assets_by_class: dict[str, list[Asset]] = {}
    for a in assets:
        assets_by_class.setdefault(a.class_code, []).append(a)

    tasks = db.session.execute(
        select(TaskDefinition).where(
            TaskDefinition.tenant_id == tenant.id,
            TaskDefinition.status == "active",
        )
    ).scalars().all()
    tasks_by_code = {t.code: t for t in tasks}

    sr_taken: set[str] = set()
    wo_taken: set[str] = set()
    insp_taken: set[str] = set()

    start = today - timedelta(days=365)

    sim_assets_water = (
        assets_by_class.get("WAT_HYD", [])
        + assets_by_class.get("WAT_MAIN", [])
        + assets_by_class.get("WAT_VLV", [])
        + assets_by_class.get("WAT_SVC", [])
    )
    sim_assets_sewer = (
        assets_by_class.get("SAN_MAIN", [])
        + assets_by_class.get("SAN_MH", [])
        + assets_by_class.get("SAN_LFT", [])
    )
    sim_assets_storm = assets_by_class.get("STM_CB", []) + assets_by_class.get(
        "STM_MAIN", []
    )
    sim_assets_any = assets

    domain_assets = {
        "water": sim_assets_water or sim_assets_any,
        "sewer": sim_assets_sewer or sim_assets_any,
        "storm": sim_assets_storm or sim_assets_any,
        "any": sim_assets_any,
    }

    # ---- Service requests + dispatched WOs ----
    target_srs = 150
    for i in range(target_srs):
        day_offset = rng.randint(0, 364)
        day_of_year = day_offset
        when = _random_business_dt(rng, start + timedelta(days=day_offset))
        category, domain, priority = _pick_sr_mix(rng, day_of_year)
        candidate_assets = domain_assets[domain] or sim_assets_any
        asset = rng.choice(candidate_assets) if candidate_assets else None

        sr = ServiceRequest(
            tenant_id=tenant.id,
            sr_number=_next_sr_number(db.session, tenant.id, sr_taken),
            category=category,
            domain=domain,
            priority=priority,
            status="new",
            reported_at=when,
            caller_name=rng.choice(CALLER_NAMES),
            caller_phone=f"555-{rng.randint(1000, 9999)}",
            reported_address=getattr(asset, "address_cached", None)
                or f"{rng.randint(10, 9999)} Main St",
            # location stays NULL — the linked asset carries the geometry
            # and the SR table column is POINT, while many assets are
            # LineString/Polygon. The UI resolves through asset_id.
            asset_id=asset.id if asset is not None else None,
            description=rng.choice(SR_DESCRIPTIONS.get(category, ["Reported issue."])),
            intake_user_id=intake.id,
            attrs=_label_simulated({}),
        )
        db.session.add(sr)
        db.session.flush()  # need id for links
        counts["sr"] += 1

        # SR lifecycle progression.
        roll = rng.random()
        if roll < 0.65:
            # Dispatched → produces a WO.
            sr.status = "dispatched"
            wo = _make_wo_from_sr(
                rng=rng,
                tenant=tenant,
                sr=sr,
                asset=asset,
                operators=operators,
                crews=crews,
                tasks_by_code=tasks_by_code,
                wo_taken=wo_taken,
                today=today,
            )
            sr.work_order_id = wo.id
            counts["wo"] += 1
            counts["time_log"] += sum(1 for _ in wo.time_logs) if wo.time_logs else 0
            counts["comment"] += wo._sim_comments_added

            # Wire SR → WO entity link.
            db.session.add(EntityLink(
                tenant_id=tenant.id,
                source_type="service_request",
                source_id=sr.id,
                target_type="work_order",
                target_id=wo.id,
                kind="caused_by",
                note="[sim] dispatched from SR",
                created_by=intake.id,
            ))
            counts["link"] += 1

            # Comment on the SR confirming dispatch.
            db.session.add(Comment(
                tenant_id=tenant.id,
                entity_type="service_request",
                entity_id=sr.id,
                body=f"[sim] Dispatched as {wo.wo_number}.",
                created_by=intake.id,
                created_at=when + timedelta(minutes=rng.randint(5, 90)),
            ))
            counts["comment"] += 1

        elif roll < 0.75:
            # Triaged but not dispatched (low-stakes / handled at intake).
            sr.status = "triaged"
            sr.closure_notes = "[sim] Resolved at intake — advised customer."
            sr.closed_at = when + timedelta(hours=rng.randint(1, 24))
            sr.closure_reason = "no_action"
            sr.status = "closed"

        elif roll < 0.85:
            # Duplicate of another SR.
            sr.status = "duplicate"
            sr.closed_at = when + timedelta(hours=rng.randint(1, 8))
            sr.closure_reason = "duplicate"

        # else: ~15% remain new (active intake queue at simulation end)

        # 1-2 comments on a fraction of SRs.
        for _ in range(rng.choices([0, 1, 2], weights=[60, 30, 10])[0]):
            db.session.add(Comment(
                tenant_id=tenant.id,
                entity_type="service_request",
                entity_id=sr.id,
                body=f"[sim] {rng.choice(['Customer called back to confirm details.', 'Spoke with neighbour — same issue reported.', 'Left voicemail with caller.'])}",
                created_by=intake.id,
                created_at=when + timedelta(hours=rng.randint(1, 48)),
            ))
            counts["comment"] += 1

        # Periodic flush so memory + ID generation stays sane.
        if i % 25 == 0:
            db.session.flush()

    # ---- Standalone (manual / scheduled) work orders ----
    target_extra_wos = 350
    for i in range(target_extra_wos):
        day_offset = rng.randint(0, 364)
        when = _random_business_dt(rng, start + timedelta(days=day_offset))
        # Pick a domain biased toward water (most common operational work).
        domain = rng.choices(
            ["water", "sewer", "storm"], weights=[5, 3, 2],
        )[0]
        candidate_assets = domain_assets[domain] or sim_assets_any
        asset = rng.choice(candidate_assets) if candidate_assets else None
        wo = _make_wo_standalone(
            rng=rng,
            tenant=tenant,
            asset=asset,
            domain=domain,
            operators=operators,
            crews=crews,
            tasks_by_code=tasks_by_code,
            wo_taken=wo_taken,
            today=today,
            when=when,
        )
        counts["wo"] += 1
        counts["time_log"] += len(wo.time_logs)
        counts["comment"] += wo._sim_comments_added

        # Some WOs spawn follow-up children — exercise parent_of links.
        if rng.random() < 0.08:
            child = _make_wo_standalone(
                rng=rng,
                tenant=tenant,
                asset=asset,
                domain=domain,
                operators=operators,
                crews=crews,
                tasks_by_code=tasks_by_code,
                wo_taken=wo_taken,
                today=today,
                when=when + timedelta(days=rng.randint(1, 14)),
            )
            counts["wo"] += 1
            counts["time_log"] += len(child.time_logs)
            counts["comment"] += child._sim_comments_added
            db.session.add(EntityLink(
                tenant_id=tenant.id,
                source_type="work_order",
                source_id=wo.id,
                target_type="work_order",
                target_id=child.id,
                kind="parent_of",
                note="[sim] follow-up spawned from parent",
                created_by=operators[0].id,
            ))
            counts["link"] += 1

        if i % 25 == 0:
            db.session.flush()

    # ---- Inspections ----
    target_inspections = 280
    for i in range(target_inspections):
        day_offset = rng.randint(0, 364)
        when = _random_business_dt(rng, start + timedelta(days=day_offset))
        kind = _pick_inspection_kind(rng)
        hint_class = INSPECTION_CLASS_HINT[kind]
        candidate_assets = assets_by_class.get(hint_class) or sim_assets_any
        asset = rng.choice(candidate_assets) if candidate_assets else None
        operator = rng.choice(operators)
        condition = rng.randint(1, 5)
        ins = Inspection(
            tenant_id=tenant.id,
            inspection_number=_next_inspection_number(db.session, tenant.id, insp_taken),
            kind=kind,
            asset_id=asset.id if asset else None,
            performed_at=when,
            performed_by=operator.id,
            overall_condition=condition,
            pass_=condition <= 3,
            notes=rng.choice([
                "[sim] Routine inspection. No issues.",
                "[sim] Minor surface corrosion noted on frame.",
                "[sim] Sediment level above threshold — schedule cleaning.",
                "[sim] All measurements within tolerance.",
            ]),
            data={"simulated": True},
            attrs=_label_simulated({}),
        )
        db.session.add(ins)
        counts["inspection"] += 1
        if i % 50 == 0:
            db.session.flush()

    db.session.commit()
    return counts


def _make_wo_from_sr(
    *, rng, tenant, sr, asset, operators, crews, tasks_by_code, wo_taken, today,
):
    when = sr.reported_at + timedelta(hours=rng.randint(1, 24))
    task = _maybe_pick_task(rng, tasks_by_code, sr.category)
    category = task.default_category if task and task.default_category else (
        "investigation" if sr.domain == "water" else "cleaning"
    )
    return _make_wo(
        rng=rng,
        tenant=tenant,
        wo_taken=wo_taken,
        wo_number=_next_wo_number(db.session, tenant.id, wo_taken),
        title=f"{sr.category.replace('_', ' ').title()} — {sr.reported_address or 'unknown'}",
        category=category,
        priority=sr.priority,
        domain=sr.domain,
        asset=asset,
        task=task,
        operators=operators,
        crews=crews,
        scheduled_for=when,
        today=today,
        service_request_id=sr.id,
        wo_type="reactive",
    )


def _make_wo_standalone(
    *, rng, tenant, asset, domain, operators, crews, tasks_by_code, wo_taken, today, when,
):
    wo_type = rng.choices(["planned", "reactive"], weights=[6, 4])[0]
    if wo_type == "planned":
        # Planned work usually has a task definition (e.g. valve exercising).
        choices = [
            ("WAT-TASK-VALVE-EXERCISE", "valve_exercise"),
            ("WAT-TASK-HYDRANT-FLUSH", "flushing"),
            ("WAT-TASK-HYDRANT-FLOW", "inspection"),
            ("SEW-TASK-LIFT-STATION", "inspection"),
            ("SEW-TASK-MANHOLE-INSPECT", "inspection"),
            ("STM-TASK-CB-INSPECT", "inspection"),
        ]
        code, category = rng.choice(choices)
        task = tasks_by_code.get(code)
    else:
        # Reactive but not from an SR — eg supervisor created it.
        code = rng.choice([
            "WAT-TASK-VALVE-EXERCISE",
            "WAT-TASK-MAIN-BREAK",
            "SEW-TASK-BACKUP",
            "SEW-TASK-SLOW-DRAIN",
            "STM-TASK-CB-CLOGGED",
            None,
        ])
        task = tasks_by_code.get(code) if code else None
        category = (task.default_category if task and task.default_category else "repair")

    title = (task.title if task else "Field work") + (
        f" — {asset.asset_uid}" if asset else ""
    )
    return _make_wo(
        rng=rng,
        tenant=tenant,
        wo_taken=wo_taken,
        wo_number=_next_wo_number(db.session, tenant.id, wo_taken),
        title=title,
        category=category,
        priority=rng.choices(["low", "normal", "high"], weights=[2, 7, 2])[0],
        domain=domain,
        asset=asset,
        task=task,
        operators=operators,
        crews=crews,
        scheduled_for=when,
        today=today,
        wo_type=wo_type,
    )


def _make_wo(
    *, rng, tenant, wo_taken, wo_number, title, category, priority, domain,
    asset, task, operators, crews, scheduled_for, today, wo_type,
    service_request_id=None,
):
    operator = rng.choice(operators)
    crew = rng.choice(crews) if crews and rng.random() < 0.5 else None
    # Decide a final status with realistic mix.
    final = rng.choices(
        ["completed", "completed", "completed", "completed", "completed",
         "in_progress", "open", "assigned", "on_hold", "cancelled", "draft"],
        k=1,
    )[0]

    started_at = None
    completed_at = None
    if final in {"in_progress", "completed", "on_hold", "cancelled"}:
        started_at = scheduled_for + timedelta(hours=rng.randint(1, 18))
    if final == "completed":
        completed_at = (started_at or scheduled_for) + timedelta(
            hours=rng.randint(1, 12)
        )
        if completed_at > today:
            completed_at = today - timedelta(hours=1)

    task_data: dict[str, Any] = {}
    if task and task.code in TASK_DATA_PRESETS and final == "completed":
        task_data = dict(rng.choice(TASK_DATA_PRESETS[task.code]))

    wo = WorkOrder(
        tenant_id=tenant.id,
        wo_number=wo_number,
        type=wo_type,
        category=category,
        priority=priority,
        status=final,
        title=title,
        description=f"[sim] {title}",
        asset_id=asset.id if asset else None,
        # See SR comment above — location is POINT-only; rely on asset_id.
        service_request_id=service_request_id,
        scheduled_for=scheduled_for,
        started_at=started_at,
        completed_at=completed_at,
        assigned_to=operator.id if final not in {"draft", "cancelled"} else None,
        crew_id=crew.id if crew else None,
        task_definition_id=task.id if task else None,
        task_data=task_data,
        attrs=_label_simulated({"domain": domain}),
    )
    db.session.add(wo)
    db.session.flush()

    # Time logs for in-progress / completed WOs.
    if final in {"in_progress", "completed"} and started_at:
        n_logs = rng.choices([1, 2, 3], weights=[5, 4, 2])[0]
        cursor = started_at
        end_cap = completed_at or (started_at + timedelta(hours=4))
        for j in range(n_logs):
            seg_hours = rng.choice([0.5, 0.75, 1.0, 1.5, 2.0])
            seg_end = min(cursor + timedelta(hours=seg_hours), end_cap)
            if seg_end <= cursor:
                break
            db.session.add(WorkOrderTimeLog(
                work_order_id=wo.id,
                user_id=operator.id,
                started_at=cursor,
                ended_at=seg_end,
                hours_decimal=Decimal(
                    f"{(seg_end - cursor).total_seconds() / 3600:.2f}"
                ),
                notes=f"[sim] {rng.choice(['On site', 'Travel + setup', 'Repair work', 'Cleanup'])}",
            ))
            cursor = seg_end + timedelta(minutes=rng.randint(0, 30))
            if cursor >= end_cap:
                break

    # Operator comments on completed WOs — exercise the comment timeline
    # without depending on the smart-comment chip UI (the operator could
    # have typed any of these).
    wo._sim_comments_added = 0  # type: ignore[attr-defined]
    if final == "completed":
        comment_count = rng.choices([0, 1, 2], weights=[2, 5, 3])[0]
        for j in range(comment_count):
            body = rng.choice([
                "[sim] Arrived on site. Customer briefed.",
                "[sim] Work complete. Customer satisfied.",
                "[sim] No further action required.",
                "[sim] Notified supervisor of finding.",
            ])
            db.session.add(Comment(
                tenant_id=tenant.id,
                entity_type="work_order",
                entity_id=wo.id,
                body=body,
                created_by=operator.id,
                created_at=(started_at or scheduled_for)
                    + timedelta(minutes=rng.randint(15, 240)),
            ))
            wo._sim_comments_added += 1  # type: ignore[attr-defined]

    return wo


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def register(app: Flask) -> None:
    @app.cli.command("simulate-year")
    @click.option("--tenant", "tenant_slug", default=DEMO_SLUG, show_default=True)
    @click.option("--seed", type=int, default=42, show_default=True)
    @click.option("--force", is_flag=True, help="Wipe simulated rows first.")
    @with_appcontext
    def simulate_year(tenant_slug: str, seed: int, force: bool):
        tenant = db.session.scalar(
            select(Tenant)
            .where(Tenant.slug == tenant_slug)
            .execution_options(skip_tenant_filter=True)
        )
        if tenant is None:
            raise click.UsageError(f"Tenant {tenant_slug!r} not found")

        already = db.session.scalar(
            select(WorkOrder.id).where(
                WorkOrder.tenant_id == tenant.id,
                WorkOrder.attrs["simulated"].astext.cast(db.Boolean) == True,  # noqa: E712
            ).limit(1)
        )
        if already and not force:
            raise click.UsageError(
                "Tenant already has simulated rows. Re-run with --force to wipe them."
            )
        if force:
            click.echo("Wiping previous simulation…")
            _wipe_simulated(tenant.id)

        click.echo(f"Simulating 12 months of work for {tenant_slug!r} (seed={seed})…")
        today = datetime.now(UTC)
        counts = _simulate(tenant, seed=seed, today=today)
        click.echo("\n".join([
            "",
            "Done.",
            f"  Service requests : {counts['sr']}",
            f"  Work orders      : {counts['wo']}",
            f"  Time logs        : {counts['time_log']}",
            f"  Inspections      : {counts['inspection']}",
            f"  Comments         : {counts['comment']}",
            f"  Entity links     : {counts['link']}",
        ]))
